
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>
  database: <%= ENV['PGHOST'] %>
  host: <%= ENV['PGHOST'] %>

development:
  <<: *default
  database: db
  database: <%= ENV['PGHOST'] %>

test:
  <<: *default
  database: db

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
